Fixing regression around wifi_connect() where PyUI was crashing with error `AttributeError: 'function' object has no attribute 'force_refresh'` when enabling wifi.
Also threw in some logging that helped me debug what was going on here.